services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: k+l0Wx1wV3Ava4eXwy94AmUiymN7lx4w/pKO5H4od1uOwSuAGc5oVFghZg0p9c5cCxfp6HMzgCcYd48OACeCAMshW+srD/fb16m9DaNnS+DhlIFBXZ5WwC1O5xayOlw0MoNpUwO575G5E3qOK/kPgj9jOJZQ805DtblzKzTXReyYidgXjS2MrBGl62ugKSQwqAT65XxWNw4vYwM1WIClbI2aVdjUJjRJOXXAwIF5sxivkcxE3oL5hYxQ0H01HTwCyyR1lEdwLAH5Bb6PSDRpWZo3tVa+MtkO4NjQo78YA8phZ0S+dKjkOP1YBZkAuVAScTCMzBYVevufURGdjIPVYgYFEJ2NUggm6LSKZ4bQllEGZLDuE3encHJJ1jCl2Cdmhdds1ZEefv3jpmXeeiLAM6RKZudw63MjJb62QfhVUD/0EaRygZSH1v9abnqboC1CnmmAgxhxKnZLQavlxkO7r2ZmiY3d2tRBPzxh4zNyKm8vYemqyFkrzTiepHB5khh3aA3jerZtAv5gQNgnicicncPXBgjohdAWcaC0X/pDhmqlKMJ3cJ9yWYYjq2Mt9aFCJr1UmYaCEVY+7Qxp07UaOgW0LE6kjXflFUiSKNPySNGXzio/sHq9aX5/IBA9H1mcbxGEV2lmxnGPuZpKTWb1eucrnJ8slIlRkd+fiXQGhNw=
  file: presentation.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/PresTeX
    tags: true
